### ISSUE TITLE
Installation fails on Redhat Enterprise 9.4

### ISSUE THREAD

**Issue by rattei** [grenaud/SAFARI#1]
Hello,

installation of SAFARI according to the docs:
git clone --recursive https://github.com/grenaud/SAFARI && cd SAFARI && ./source_me.sh && make -j 8 || true && make clean && make -j 8

fails on RHEL 9.4 with this error:
....
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/projects2/vgan_ancient/THIRD_VERSION/SAFARI/deps/sparsehash/missing aclocal-1.16 -I m4
/bin/bash: /home/projects2/vgan_ancient/THIRD_VERSION/SAFARI/deps/sparsehash/missing: No such file or directory

The error message indicates a hard-coded path "/home/projects2/", which does not exist on our system. Can this please be corrected? Thanks!

Best, Thomas

**Comment by JoshuaDanielRubin** [comment]
Hi Thomas,

Apologies, I tested this on the same machine that I compiled on so I didn't catch this - I will work on it, in the meantime I hope the static binary works for you.

Best,
Josh

**Comment by rattei** [comment]
Indeed, the static binary seems to work on RHEL 9.4. We can run the example from the readme (although, initially it was confusing that the example needs the SAFARI clone from GitHub, including its test folder, and additionally the SAFARI_graph as separate download).

Best, Thomas

**Comment by JoshuaDanielRubin** [comment]
It should be fixed now.
